In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import math
import operator
import csv

In [2]:
pd.options.display.max_colwidth = 250

In [3]:
from sentence_transformers import SentenceTransformer
 
model = SentenceTransformer('LazarusNLP/all-indo-e5-small-v4')

In [4]:
# Membaca file madaniyah.csv untuk mendapatkan nomor surah
madaniyah_chapters = []
with open('../madaniyah.csv', 'r') as file:
    csv_reader = csv.reader(file)
    next(csv_reader)  # Melewati header
    for row in csv_reader:
        madaniyah_chapters.append(int(row[1]))
        

sentences = []

for chapter in madaniyah_chapters:

  google_translate = pd.read_csv('../data/google_translate/chapter_' + str(chapter) + '.csv')
  kemenag = pd.read_csv('../data/kemenag/chapter_' + str(chapter) + '.csv')
  king_fahd = pd.read_csv('../data/king_fahd/chapter_' + str(chapter) + '.csv')

  sentence1 = google_translate['google_translate'].tolist()
  sentence2 = kemenag['kemenag'].tolist()
  sentence3 = king_fahd['king_fahd'].tolist()

  sentences.append(sentence1)
  sentences.append(sentence2)
  sentences.append(sentence3)


sentence_new = []
for i in range(0, len(sentences)):
  for j in range(0, len(sentences[i])):
    sentence_new.append(sentences[i][j])

sentence_embeddings = model.encode(sentence_new)

In [5]:
sentence_embeddings.shape

(3897, 384)

In [6]:
# Inisialisasi
index_map = []
current_index = 0
df = pd.DataFrame(columns=[
    'Chapter', 'Verse', 'Google Translate', 'Kemenag', 'King Fahd',
    'Fahd - Google', 'Kemenag - Google', 'Fahd - Kemenag'
])

# Bangun peta indeks untuk masing-masing surah
for chapter in madaniyah_chapters:
    df_chapter = pd.read_csv(f'../data/google_translate/chapter_{chapter}.csv')

    n_verses = len(df_chapter)

    index_map.append({
        'chapter': chapter,
        'start_index': current_index,
        'num_verses': n_verses
    })

    current_index += 3 * n_verses  # 3 versi: king_fahd, kemenag, google

# Loop seluruh surah dan ayat untuk hitung similarity
for mapping in index_map:
    chapter = mapping['chapter']
    start = mapping['start_index']
    n_verses = mapping['num_verses']

    for verse in range(n_verses):
        i_google = start + verse
        i_kemenag = start + n_verses + verse
        i_fahd = start + 2 * n_verses + verse

        # Hitung cosine similarity
        sim_fahd = cosine_similarity([sentence_embeddings[i_fahd]], [sentence_embeddings[i_google]])[0][0]
        sim_kemenag = cosine_similarity([sentence_embeddings[i_kemenag]], [sentence_embeddings[i_google]])[0][0]
        sim_fahd_kemenag = cosine_similarity([sentence_embeddings[i_fahd]], [sentence_embeddings[i_kemenag]])[0][0]

        dict_row = {
            'Chapter': chapter,
            'Verse': verse + 1,
            'Google Translate': sentence_new[i_google],
            'Kemenag': sentence_new[i_kemenag],
            'King Fahd': sentence_new[i_fahd],
            'Fahd - Google': sim_fahd,
            'Kemenag - Google': sim_kemenag,
            'Fahd - Kemenag': sim_fahd_kemenag
        }

        df = pd.concat([df, pd.DataFrame([dict_row])], ignore_index=True)

# Tampilkan hasil akhir
df

/var/folders/p8/hpcxrgfd4wv_j3fp535z1ytc0000gn/T/ipykernel_93284/2195464410.py:50: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([dict_row])], ignore_index=True)

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000
1,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244
2,2,3,"Orang-orang yang beriman kepada yang gaib, mendirikan shalat, dan menafkahkan sebagian rezeki yang Kami berikan kepada mereka.","(Yaitu) mereka yang beriman kepada yang gaib, melaksanakan salat, dan menginfakkan sebagian rezeki yang Kami berikan kepada mereka,","(yaitu) mereka yang beriman kepada yang gaib, yang mendirikan salat, dan menafkahkan sebagian rezeki yang Kami anugerahkan kepada mereka,",0.901631,0.898958,0.975567
3,2,4,"Dan orang-orang yang beriman kepada kitab yang diturunkan kepadamu dan kitab yang diturunkan sebelum kamu, dan kepada kehidupan akhirat, mereka adalah yakin.","dan mereka beriman kepada (Alquran) yang diturunkan kepadamu (Muhammad) dan (kitab-kitab) yang telah diturunkan sebelum engkau, dan mereka yakin akan adanya akhirat.","dan mereka yang beriman kepada Kitab (Al-Qur`ān) yang telah diturunkan kepadamu dan kitab-kitab yang telah diturunkan sebelummu, serta mereka yakin akan adanya (kehidupan) akhirat.",0.909239,0.857523,0.920318
4,2,5,Mereka itulah yang mendapat petunjuk dari Tuhannya dan mereka itulah orang-orang yang beruntung.,"Merekalah yang mendapat petunjuk dari Tuhannya, dan mereka itulah orang-orang yang beruntung.","Mereka itulah yang tetap mendapat petunjuk dari Tuhan mereka, dan merekalah orang-orang yang beruntung.",0.931456,0.992417,0.932781
...,...,...,...,...,...,...,...,...
1294,66,8,"Wahai orang-orang yang beriman, bertobatlah kepada Allah dengan taubat yang tulus. Mudah-mudahan Tuhanmu akan menghapus kesalahan-kesalahanmu dan memasukkanmu ke dalam surga yang mengalir di bawahnya sungai-sungai, pada hari ketika Allah tidak ak...","Wahai orang-orang yang beriman! Bertobatlah kepada Allah dengan tobat yang semurni-murninya, mudah-mudahan Tuhan kamu akan menghapus kesalahan-kesalahanmu dan memasukkan kamu ke dalam surga-surga yang mengalir di bawahnya sungai-sungai, pada hari...","Hai orang-orang yang beriman, bertobatlah kepada Allah dengan tobat yang semurni-murninya, mudah-mudahan Tuhan kamu akan menghapus kesalahan-kesalahanmu dan memasukkanmu ke dalam surga yang mengalir di bawahnya sungai-sungai, pada hari ketika All...",0.907043,0.875991,0.928247
1295,66,9,"Wahai Nabi, perangilah orang-orang kafir dan munafik, dan bersikaplah keras terhadap mereka. Tempat kembali mereka adalah neraka, dan seburuk-buruk tempat kembali.",Wahai Nabi! Perangilah orang-orang kafir dan orang-orang munafik dan bersikap keraslah terhadap mereka. Tempat mereka adalah neraka Jahanam dan itulah seburuk-buruk tempat kembali.,"Hai Nabi, perangilah orang-orang kafir dan orang-orang munafik dan bersikap keraslah terhadap mereka. Tempat mereka adalah jahanam dan itu adalah seburuk-buruknya tempat kembali.",0.913609,0.960408,0.928341
1296,66,10,"Allah menjadikan istri Nuh dan istri Luth sebagai perumpamaan bagi orang-orang yang kafir. Keduanya berada di bawah pengawasan dua hamba Kami yang saleh, lalu keduanya mengkhianati keduanya, maka keduanya tidak dapat menolong mereka sedikit pun ...","Allah membuat perumpamaan bagi orang-orang kafir, istri Nuh dan istri Luṭ. Keduanya berada di bawah pengawasan dua orang hamba yang saleh di antara hamba-hamba Kami; lalu kedua istri itu berkhianat kepada kedua suaminya, tetapi kedua suaminya itu...","Allah membuat istri Nūḥ dan istri Lūṭ sebagai perumpamaan bagi orang-orang kafir. Keduanya berada di bawah pengawasan dua orang hamba yang saleh di antara hamba-hamba Kami; lalu kedua istri itu berkhianat kepada kedua suaminya, maka kedua suamin...",0.904372,0.954068,0.930484
1297,66,11,"Dan Allah menjadikan perumpamaan bagi orang-orang yang beriman, yaitu istri Fir'aun, ketika ia berdoa: ""Ya Tuhanku, bangunkanlah untukku sebuah rumah di sisi-Mu di surga dan peliharalah aku dari Fir'aun dan perbuatannya, dan peliharalah aku dari ...","Dan Allah membuat perumpamaan bagi orang-orang yang beriman, istri Fir'aun, ketika dia berkata, ""Ya Tuhanku, bangunkanlah untukku satu rumah di sisi-Mu dalam surga dan selamatkanlah aku dari Fir'aun dan perbuatannya, dan selamatkanlah aku dari ka...","Dan Allah membuat istri Firʻawn perumpamaan bagi orang-orang yang beriman, ketika ia berkata, ""Ya Tuhan-ku, bangunlah untukku sebuah rumah di sisi-Mu dalam surga dan selamatkanlah aku dari Firʻawn dan perbuatannya, dan selamatkanlah aku dari ka...",0.956486,0.966203,0.973615
1298,66,12,"Dan Maryam putri Imran, yang menjaga kehormatannya, lalu Kami tiupkan ke dalam dirinya sebagian dari roh Kami, lalu dia beriman kepada kalimat-kalimat Tuhannya dan Kitab-kitab-Nya, dan dia termasuk orang-orang yang bertaqwa.","dan Maryam putri Imran yang memelihara kehormatannya, maka Kami tiupkan ke dalam rahimnya sebagian dari roh (ciptaan) Kami; dan dia membenarkan kalimat-kalimat Tuhannya dan kitab-kitab-Nya; dan dia termasuk orang-orang yang taat.","dan Maryam putri ʻImrān yang memelihara kehormatannya, maka Kami tiupkan ke dalam rahimnya sebagian dari roh (ciptaan) Kami, dan dia membenarkan kalimat-kalimat Tuhan-nya dan Kitab-kitab-Nya, dan adalah dia termasuk orang-orang yang taat.",0.843941,0.913286,0.927419

In [7]:
df.to_csv('../Semantic Analysis Results/cosine_similarity.csv', index=False)

## BLEU SCORE

In [ ]:
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

In [ ]:
bleu_kemenag_google = []
bleu_fahd_google = []
bleu_fahd_kemenag = []

# Smoothing function membantu menghindari skor 0 untuk kalimat pendek
chencherry = SmoothingFunction()

# Iterasi melalui setiap baris DataFrame untuk menghitung skor
for index, row in df.iterrows():
    # Tokenisasi (memecah kalimat menjadi kata-kata)
    # Referensi harus dalam format list of lists: [[kata1, kata2, ...]]
    ref_google = [row['Google Translate'].split()]
    ref_kemenag = [row['Kemenag'].split()]
    
    # Kandidat adalah list kata-kata: [kata1, kata2, ...]
    candidate_kemenag = row['Kemenag'].split()
    candidate_fahd = row['King Fahd'].split()

    # Hitung skor BLEU untuk Kemenag (kandidat) vs Google (referensi)
    score_kg = sentence_bleu(ref_google, candidate_kemenag, smoothing_function=chencherry.method1)
    bleu_kemenag_google.append(score_kg)

    # Hitung skor BLEU untuk King Fahd (kandidat) vs Google (referensi)
    score_fg = sentence_bleu(ref_google, candidate_fahd, smoothing_function=chencherry.method1)
    bleu_fahd_google.append(score_fg)
    
    # Hitung skor BLEU untuk King Fahd (kandidat) vs Kemenag (referensi)
    score_fk = sentence_bleu(ref_kemenag, candidate_fahd, smoothing_function=chencherry.method1)
    bleu_fahd_kemenag.append(score_fk)

# Tambahkan kolom baru berisi skor BLEU ke DataFrame
df['BLEU Kemenag-Google'] = bleu_kemenag_google
df['BLEU Fahd-Google'] = bleu_fahd_google
df['BLEU Fahd-Kemenag'] = bleu_fahd_kemenag

# Tampilkan DataFrame dengan kolom skor semantik dan skor BLEU
# Anda dapat menampilkan seluruh df atau hanya beberapa kolom untuk verifikasi
pd.set_option('display.max_rows', 10) # Mengatur tampilan agar tidak terlalu panjang
display(df[[
    'Chapter', 'Verse', 
    'Fahd - Google', 'BLEU Fahd-Google',
    'Kemenag - Google', 'BLEU Kemenag-Google',
    'Fahd - Kemenag', 'BLEU Fahd-Kemenag'
]])

### Menemukan Perbedaan Maksimal

In [8]:
maximum_difference_fahd_google = df.loc[(df['Fahd - Google'] < 0.5)]

maximum_difference_fahd_google

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000
286,3,1,nyeri,Alif lām Mīm.,Alif Lām Mīm.,0.010567,0.125248,0.824753
339,3,54,"Dan mereka berencana, dan Allah pun berencana. Dan Allah adalah sebaik-baik perencana.","Dan mereka (orang-orang kafir) membuat tipu daya, maka Allah pun membalas tipu daya. Dan Allah sebaik-baik pembalas tipu daya.","Orang-orang kafir itu membuat tipu daya, dan Allah membalas tipu daya mereka itu. Dan Allah sebaik-baik pembalas tipu daya.",0.447102,0.476180,0.945183
583,4,98,"Kecuali orang-orang tertindas di antara laki-laki, perempuan, dan anak-anak yang tidak dapat merancang rencana dan juga tidak ditunjukkan jalan.","Kecuali mereka yang tertindas baik laki-laki atau perempuan dan anak-anak yang tidak berdaya dan tidak mengetahui jalan (untuk berhijrah),","kecuali mereka yang tertindas, baik laki-laki atau wanita ataupun anak-anak yang tidak mampu berdaya upaya dan tidak mengetahui jalan (untuk hijrah),",0.493049,0.612253,0.825672
818,9,37,"Interkalasi hanyalah penambahan kekufuran yang dengannya orang-orang kafir disesatkan. Mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain agar mereka dapat menyempurnakan apa yang diharamkan Allah, dan dengan demikia...","Sesungguhnya pengunduran (bulan haram) itu hanya menambah kekafiran. Orang-orang kafir disesatkan dengan (pengunduran) itu, mereka menghalalkannya satu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menyesuaikan dengan bilangan...","Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menses...",0.346780,0.354384,0.879055
959,24,49,"Dan jika kebenaran itu milik mereka, mereka akan menerimanya dengan berserah diri.","Tetapi, jika kebenaran dipihak mereka, mereka datang kepadanya (Rasul) dengan patuh.","Tetapi jika keputusan itu untuk (kemaslahatan) mereka, mereka datang kepada rasul dengan patuh.",0.314125,0.711123,0.525156
988,33,14,"Dan jika surga itu datang kepada mereka dari daerahnya, kemudian mereka diminta untuk mengujinya, niscaya mereka akan mengujinya, dan mereka tidak akan tinggal di dalamnya kecuali sebentar saja.","Dan kalau (Yasrib) diserang dari segala penjuru, dan mereka diminta agar membuat kekacauan, niscaya mereka mengerjakannya; dan hanya sebentar saja mereka menunggu.","Kalau (Yaṡrib) diserang dari segala penjuru, kemudian diminta kepada mereka supaya murtad , niscaya mereka mengerjakannya dan mereka tiada akan menunda untuk murtad itu, melainkan dalam waktu yang singkat.",0.438173,0.428026,0.772614

In [9]:
maximum_difference_kemenag_google = df.loc[(df['Kemenag - Google'] < 0.5)]

maximum_difference_kemenag_google

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000
286,3,1,nyeri,Alif lām Mīm.,Alif Lām Mīm.,0.010567,0.125248,0.824753
339,3,54,"Dan mereka berencana, dan Allah pun berencana. Dan Allah adalah sebaik-baik perencana.","Dan mereka (orang-orang kafir) membuat tipu daya, maka Allah pun membalas tipu daya. Dan Allah sebaik-baik pembalas tipu daya.","Orang-orang kafir itu membuat tipu daya, dan Allah membalas tipu daya mereka itu. Dan Allah sebaik-baik pembalas tipu daya.",0.447102,0.476180,0.945183
818,9,37,"Interkalasi hanyalah penambahan kekufuran yang dengannya orang-orang kafir disesatkan. Mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain agar mereka dapat menyempurnakan apa yang diharamkan Allah, dan dengan demikia...","Sesungguhnya pengunduran (bulan haram) itu hanya menambah kekafiran. Orang-orang kafir disesatkan dengan (pengunduran) itu, mereka menghalalkannya satu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menyesuaikan dengan bilangan...","Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menses...",0.346780,0.354384,0.879055
918,24,8,"Dan mereka menangkal azab itu dengan memberi kesaksian empat kali atas nama Allah, bahwa sesungguhnya dia termasuk orang-orang yang berdusta.","Dan istri itu terhindar dari hukuman apabila dia bersumpah empat kali atas (nama) Allah bahwa dia (suaminya) benar-benar termasuk orang-orang yang berdusta,",Istrinya itu dihindarkan dari hukuman oleh sumpahnya empat kali atas nama Allah; sesungguhnya suaminya itu benar-benar termasuk orang-orang yang dusta.,0.542857,0.490454,0.891828
988,33,14,"Dan jika surga itu datang kepada mereka dari daerahnya, kemudian mereka diminta untuk mengujinya, niscaya mereka akan mengujinya, dan mereka tidak akan tinggal di dalamnya kecuali sebentar saja.","Dan kalau (Yasrib) diserang dari segala penjuru, dan mereka diminta agar membuat kekacauan, niscaya mereka mengerjakannya; dan hanya sebentar saja mereka menunggu.","Kalau (Yaṡrib) diserang dari segala penjuru, kemudian diminta kepada mereka supaya murtad , niscaya mereka mengerjakannya dan mereka tiada akan menunda untuk murtad itu, melainkan dalam waktu yang singkat.",0.438173,0.428026,0.772614

In [10]:
maximum_difference = df.loc[(df['Fahd - Google'] < 0.5) & (df['Kemenag - Google'] < 0.5)]

maximum_difference

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000
286,3,1,nyeri,Alif lām Mīm.,Alif Lām Mīm.,0.010567,0.125248,0.824753
339,3,54,"Dan mereka berencana, dan Allah pun berencana. Dan Allah adalah sebaik-baik perencana.","Dan mereka (orang-orang kafir) membuat tipu daya, maka Allah pun membalas tipu daya. Dan Allah sebaik-baik pembalas tipu daya.","Orang-orang kafir itu membuat tipu daya, dan Allah membalas tipu daya mereka itu. Dan Allah sebaik-baik pembalas tipu daya.",0.447102,0.476180,0.945183
818,9,37,"Interkalasi hanyalah penambahan kekufuran yang dengannya orang-orang kafir disesatkan. Mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain agar mereka dapat menyempurnakan apa yang diharamkan Allah, dan dengan demikia...","Sesungguhnya pengunduran (bulan haram) itu hanya menambah kekafiran. Orang-orang kafir disesatkan dengan (pengunduran) itu, mereka menghalalkannya satu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menyesuaikan dengan bilangan...","Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menses...",0.346780,0.354384,0.879055
988,33,14,"Dan jika surga itu datang kepada mereka dari daerahnya, kemudian mereka diminta untuk mengujinya, niscaya mereka akan mengujinya, dan mereka tidak akan tinggal di dalamnya kecuali sebentar saja.","Dan kalau (Yasrib) diserang dari segala penjuru, dan mereka diminta agar membuat kekacauan, niscaya mereka mengerjakannya; dan hanya sebentar saja mereka menunggu.","Kalau (Yaṡrib) diserang dari segala penjuru, kemudian diminta kepada mereka supaya murtad , niscaya mereka mengerjakannya dan mereka tiada akan menunda untuk murtad itu, melainkan dalam waktu yang singkat.",0.438173,0.428026,0.772614

peneliti menyadari pada chapter 2 dan 3 ayat 1 terdapat nilai cosine yang bernilai 0.
setelah dicari lebih lanjut, menurut para ahli, ayat-ayat tersebut memang tidak memiliki arti sehingga penerjemahannya ke bahasa indonesia pun tidak bisa diketahui dan para ahli sepakat untuk menerjemahkannya sesuai suara ayat tersebut. 
ini adalah apa

Mengapa Ayat Ini Tidak Layak Dianalisis secara Semantik:
1. Tidak Memiliki Makna Linguistik yang Diketahui Ulama dan ahli tafsir sepakat bahwa huruf-huruf muqattaʿat ini tidak diketahui maknanya secara pasti, dan hanya Allah SWT yang mengetahui maksudnya. Maka, tidak ada padanan semantik yang bisa diukur, baik oleh manusia maupun mesin.
2. Diterjemahkan Sebagai Pelafalan Bunyi, Bukan Makna Karena tidak memiliki arti semantik, para penerjemah Al-Qur’an memilih menuliskan huruf-huruf tersebut sesuai pengucapannya, seperti “Alif Lam Mim”, dan bukan menerjemahkannya dalam bentuk kata bermakna.
3. Google Translate Menerjemahkan Secara Salah dan Kontekstual Tidak Sah Google Translate, yang bekerja berdasarkan model data umum, menyalahartikan huruf-huruf tersebut menjadi kata-kata yang tidak relevan, seperti "nyeri", karena tidak memahami konteks wahyu. Ini menghasilkan nilai cosine yang rendah secara teknis, tetapi bukan karena ketidakcocokan makna, melainkan karena metode yang tidak sesuai.

In [15]:
cleaning = pd.read_csv('../Semantic Analysis Results/cosine_similarity.csv')

cleaning = cleaning.drop([0, 286])
cleaning = cleaning.reset_index(drop=True)
cleaning.head()

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
0,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244
1,2,3,"Orang-orang yang beriman kepada yang gaib, mendirikan shalat, dan menafkahkan sebagian rezeki yang Kami berikan kepada mereka.","(Yaitu) mereka yang beriman kepada yang gaib, melaksanakan salat, dan menginfakkan sebagian rezeki yang Kami berikan kepada mereka,","(yaitu) mereka yang beriman kepada yang gaib, yang mendirikan salat, dan menafkahkan sebagian rezeki yang Kami anugerahkan kepada mereka,",0.901631,0.898958,0.975567
2,2,4,"Dan orang-orang yang beriman kepada kitab yang diturunkan kepadamu dan kitab yang diturunkan sebelum kamu, dan kepada kehidupan akhirat, mereka adalah yakin.","dan mereka beriman kepada (Alquran) yang diturunkan kepadamu (Muhammad) dan (kitab-kitab) yang telah diturunkan sebelum engkau, dan mereka yakin akan adanya akhirat.","dan mereka yang beriman kepada Kitab (Al-Qur`ān) yang telah diturunkan kepadamu dan kitab-kitab yang telah diturunkan sebelummu, serta mereka yakin akan adanya (kehidupan) akhirat.",0.909239,0.857523,0.920318
3,2,5,Mereka itulah yang mendapat petunjuk dari Tuhannya dan mereka itulah orang-orang yang beruntung.,"Merekalah yang mendapat petunjuk dari Tuhannya, dan mereka itulah orang-orang yang beruntung.","Mereka itulah yang tetap mendapat petunjuk dari Tuhan mereka, dan merekalah orang-orang yang beruntung.",0.931456,0.992417,0.932781
4,2,6,"Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, engkau (Muhammad) beri peringatan atau tidak engkau beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.",1.000000,0.977054,0.977054

In [16]:
cleaning.to_csv('../Semantic Analysis Results/cosine_similarity.csv')

In [17]:
maximum_difference_fahd_kemenang = df.loc[(df['Fahd - Kemenag'] < 0.5)]
maximum_difference_fahd_kemenang

Empty DataFrame
Columns: [Chapter, Verse, Google Translate, Kemenag, King Fahd, Fahd - Google, Kemenag - Google, Fahd - Kemenag]
Index: []

In [18]:
print("jumlah ayat semantik rendah Fahd - Google: ", len(maximum_difference_fahd_google))
print("jumlah ayat semantik rendah Kemenag - Google: ", len(maximum_difference_kemenag_google))
print("jumlah ayat semantik rendah di kedua: ", len(maximum_difference))

jumlah ayat semantik rendah Fahd - Google:  7
jumlah ayat semantik rendah Kemenag - Google:  6
jumlah ayat semantik rendah di kedua:  5

In [19]:
df['total'] = df['Fahd - Google'] + df['Kemenag - Google']
df.head(2)

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000,0.021134
1,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244,1.861109

In [20]:
df['max sum'] = df.groupby(['Chapter'])['total'].transform('max')
df.head(2)

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total,max sum
0,2,1,nyeri,Alif Lām Mīm.,Alif Lām Mīm.,0.010567,0.010567,1.000000,0.021134,1.977054
1,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244,1.861109,1.977054

In [21]:
df_max_sum = df.loc[(df['max sum'] == df['total'])]
df_max_sum

,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total,max sum
5,2,6,"Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, engkau (Muhammad) beri peringatan atau tidak engkau beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.",1.000000,0.977054,0.977054,1.977054,1.977054
416,3,131,Dan peliharalah dirimu dari api neraka yang disediakan untuk orang-orang kafir.,"Dan peliharalah dirimu dari api neraka, yang telah disiapkan untuk orang-orang kafir.","Dan peliharalah dirimu dari api neraka, yang disediakan untuk orang-orang yang kafir.",0.992948,0.988078,0.987602,1.981026,1.981026
553,4,68,Dan Kami tunjukkan mereka kepada jalan yang lurus.,dan pasti Kami tunjukan kepada mereka jalan yang lurus.,dan pasti Kami tunjuki mereka kepada jalan yang lurus.,0.980154,0.954838,0.970797,1.934992,1.934992
747,5,86,"Dan orang-orang yang kafir dan mendustakan ayat-ayat Kami, mereka itu adalah penghuni neraka.","Dan orang-orang yang kafir serta mendustakan ayat-ayat Kami, mereka itulah penghuni neraka.","Dan orang-orang kafir serta mendustakan ayat-ayat Kami, mereka itulah penghuni neraka.",0.989377,0.992759,0.995986,1.982136,1.982136
870,9,89,"Allah telah menyediakan bagi mereka surga-surga yang mengalir di bawahnya sungai-sungai, dan mereka kekal di dalamnya. Itulah kemenangan yang agung.","Allah telah menyediakan bagi mereka surga yang mengalir di bawahnya sungai-sungai, mereka kekal di dalamnya. Itulah kemenangan yang agung.","Allah telah menyediakan bagi mereka surga yang mengalir di bawahnya sungai-sungai, mereka kekal di dalamnya. Itulah kemenangan yang besar.",0.959270,0.988579,0.973153,1.947849,1.947849
944,24,34,"Dan sungguh, Kami telah turunkan kepadamu ayat-ayat yang menjelaskan kepadamu, dan contoh dari orang-orang terdahulu sebelum kamu, dan pelajaran bagi orang-orang yang bertakwa.","Dan sungguh, Kami telah menurunkan kepada kamu ayat-ayat yang memberi penjelasan, dan contoh-contoh dari orang-orang yang terdahulu sebelum kamu dan sebagai pelajaran bagi orang-orang yang bertakwa.",Dan sesungguhnya Kami telah menurunkan kepada kamu ayat-ayat yang memberi penerangan dan contoh-contoh dari orang-orang yang terdahulu sebelum kamu dan pelajaran bagi orang-orang yang bertakwa.,0.956758,0.973387,0.957617,1.930145,1.930145
1016,33,42,"Dan bertasbihlah kepada-Nya, pagi dan petang.",dan bertasbihlah kepada-Nya pada waktu pagi dan petang.,Dan bertasbihlah kepada-Nya pada waktu pagi dan petang.,0.985886,0.984013,0.996785,1.969899,1.969899
1054,47,7,"Hai orang-orang yang beriman, jika kamu menolong Allah, niscaya Dia akan menolong kamu dan meneguhkan kedudukanmu.","Wahai orang-orang yang beriman! Jika kamu menolong (agama) Allah, niscaya Dia akan menolongmu dan meneguhkan kedudukanmu.","Hai orang-orang yang beriman, jika kamu menolong (agama) Allah, niscaya Dia akan menolongmu dan meneguhkan kedudukanmu.",0.983254,0.946193,0.952714,1.929447,1.929447
1086,48,1,Sesungguhnya Kami telah memberikan kemenangan yang nyata kepadamu.,"Sungguh, Kami telah memberikan kepadamu kemenangan yang nyata.","Sesungguhnya Kami telah memberikan kepadamu kemenangan yang nyata,",0.976276,0.968684,0.953683,1.944959,1.944959
1132,49,18,Sesungguhnya Allah mengetahui apa yang gaib di langit dan di bumi. Dan Allah Maha Melihat apa yang kamu kerjakan.,"Sungguh, Allah mengetahui apa yang gaib di langit dan di bumi. Dan Allah Maha Melihat apa yang kamu kerjakan.",Sesungguhnya Allah mengetahui apa yang gaib di langit dan bumi. Dan Allah Maha Melihat apa yang kamu kerjakan.,0.998519,0.987239,0.986964,1.985758,1.985758
1153,57,21,"Berlomba-lombalah kamu untuk mendapatkan ampunan dari Tuhanmu dan untuk mendapatkan surga yang luasnya seluas langit dan bumi, yang disediakan bagi orang-orang yang beriman kepada Allah dan para rasul-Nya. Itulah karunia Allah yang diberikan-Nya ...","Berlomba-lombalah kamu untuk mendapatkan ampunan dari Tuhanmu dan surga yang luasnya seluas langit dan bumi, yang disediakan bagi orang-orang yang beriman kepada Allah dan rasul-rasul-Nya. Itulah karunia Allah, yang diberikan kepada siapa yang Di...","Berlomba-lombalah kamu kepada (mendapatkan) ampunan dari Tuhan-mu dan surga yang luasnya seluas langit dan bumi, yang disediakan bagi orang-orang yang beriman kepada Allah dan rasul-rasul-Nya. Itulah karunia Allah, diberikan-Nya kepada siapa yan...",0.977541,0.989018,0.987933,1.966559,1.966559
1168,58,7,"Tidakkah kamu perhatikan bahwa Allah mengetahui apa yang ada di langit dan apa yang ada di bumi? Tidaklah suatu pembicaraan rahasia antara tiga orang melainkan Dialah yang keempat bagi mereka, tidak pula antara lima orang melainkan Dialah yang ke...","Tidakkah engkau perhatikan, bahwa Allah mengetahui apa yang ada di langit dan apa yang ada di bumi? Tidak ada pembicaraan rahasia antara tiga orang, melainkan Dialah yang keempatnya. Dan tidak ada lima orang, melainkan Dialah yang keenamnya. Dan ...","Tidakkah kamu perhatikan, bahwa sesungguhnya Allah mengetahui apa yang ada di langit dan apa yang ada di bumi? Tiada pembicaraan rahasia antara tiga orang, melainkan Dia-lah yang keempatnya. Dan tiada (pembicaraan antara) lima orang, melainkan D...",0.953820,0.978212,0.964406,1.932033,1.932033
1202,59,19,"Dan janganlah kamu seperti orang-orang yang melupakan Allah, lalu Allah menjadikan mereka melupakan diri mereka sendiri. Mereka itulah orang-orang yang fasik.","Dan janganlah kamu seperti orang-orang yang lupa kepada Allah, sehingga Allah menjadikan mereka lupa akan diri sendiri. Mereka itulah orang-orang fasik.","Dan janganlah kamu seperti orang-orang yang lupa kepada Allah, lalu Allah menjadikan mereka lupa kepada mereka sendiri. Mereka itulah orang-orang yang fasik.",0.960250,0.950658,0.987423,1.910908,1.910908
1215,60,8,"Allah tidak melarang kalian dari orang-orang yang tidak memerangi kalian karena agama dan tidak mengusir kalian dari kampung halaman kalian, dari berlaku baik kepada mereka dan berlaku adil kepada mereka. Sesungguhnya Allah mencintai orang-orang ...",Allah tidak melarang kamu berbuat baik dan berlaku adil terhadap orang-orang yang tidak memerangimu dalam urusan agama dan tidak mengusir kamu dari kampung halamanmu. Sesungguhnya Allah mencintai orang-orang yang berlaku adil.,Allah tiada melarang kamu untuk berbuat baik dan berlaku adil terhadap orang-orang yang tiada memerangimu karena agama dan tidak (pula) mengusir kamu dari negerimu. Sesungguhnya Allah menyukai orang-orang yang berlaku adil.,0.901367,0.954767,0.904956,1.856134,1.856134
1231,61,11,"Kamu beriman kepada Allah dan Rasul-Nya, dan berjihad di jalan Allah dengan harta dan jiwamu. Yang demikian itu lebih baik bagimu, jika kamu mengetahui.","(Yaitu) kamu beriman kepada Allah dan Rasul-Nya dan berjihad di jalan Allah dengan harta dan jiwamu. Itulah yang lebih baik bagi kamu jika kamu mengetahui,","(yaitu) kamu beriman kepada Allah dan rasul-Nya dan berjihad di jalan Allah dengan harta dan jiwamu. Itulah yang lebih baik bagi kamu, jika kamu mengetahui,",0.968638,0.972436,0.984250,1.941074,1.941074
1242,62,8,"Katakanlah, ""Sesungguhnya kematian yang kamu lari darinya, pasti akan menemuimu. Kemudian kamu akan dikembalikan kepada Yang Mengetahui akan yang ghaib dan yang nyata, lalu Dia beritakan kepadamu apa yang telah kamu kerjakan.""","Katakanlah, ""Sesungguhnya kematian yang kamu lari dari padanya, ia pasti menemui kamu, kemudian kamu akan dikembalikan kepada (Allah), yang mengetahui yang gaib dan yang nyata, lalu Dia beritakan kepadamu apa yang telah kamu kerjakan.""","Katakanlah, ""Sesungguhnya kematian yang kamu lari darinya, maka sesungguhnya kematian itu akan menemui kamu, kemudian kamu akan dikembalikan kepada (Allah), yang mengetahui yang gaib dan yang nyata, lalu Dia beritakan kepadamu apa yang telah kamu...",0.948739,0.915555,0.945107,1.864294,1.864294
1247,63,2,"Mereka menjadikan sumpah-sumpah mereka sebagai perisai dan menghalangi manusia dari jalan Allah. Sesungguhnya, amat buruk apa yang telah mereka kerjakan.","Mereka menjadikan sumpah-sumpah mereka sebagai perisai, lalu mereka menghalang-halangi (manusia) dari jalan Allah. Sungguh, betapa buruknya apa yang telah mereka kerjakan.","Mereka itu menjadikan sumpah mereka sebagai perisai, lalu mereka menghalangi (manusia) dari jalan Allah. Sesungguhnya amat buruklah apa yang telah mereka kerjakan.",0.948785,0.952092,0.946940,1.900877,1.900877
1266,64,10,"Dan orang-orang yang kafir dan mendustakan ayat-ayat Kami, mereka itu adalah penghuni-penghuni neraka; mereka kekal di dalamnya. Dan seburuk-buruk tempat kembali.","Dan orang-orang yang kafir dan mendustakan ayat-ayat Kami, mereka itulah penghuni neraka, mereka kekal di dalamnya. Dan itulah seburuk-buruk tempat kembali.","Dan orang-orang yang kafir dan mendustakan ayat-ayat Kami, mereka itulah penghuni-penghuni neraka, mereka kekal di dalamnya. Dan itulah seburuk-buruk tempat kembali.",0.991951,0.982942,0.992446,1.974893,1.974893
1279,65,5,"Itulah perintah Allah yang telah Dia turunkan kepadamu. Dan barangsiapa yang bertakwa kepada Allah, niscaya Dia akan menghapus kesalahan-kesalahannya dan memberikan pahala yang besar kepadanya.","Itulah perintah Allah yang diturunkan-Nya kepada kamu; barangsiapa bertakwa kepada Allah, niscaya Allah akan menghapus kesalahan-kesalahannya dan akan melipatgandakan pahala baginya.","Itulah perintah Allah yang diturunkan-Nya kepada kamu, dan barang siapa yang bertakwa kepada Allah, niscaya Dia akan menghapus kesalahan-kesalahannya dan akan melipatgandakan pahala baginya.",0.923027,0.947221,0.971032,1.870248,1.870248
1297,66,11,"Dan Allah menjadikan perumpamaan bagi orang-orang yang beriman, yaitu istri Fir'aun, ketika ia berdoa: ""Ya Tuhanku, bangunkanlah untukku sebuah rumah di sisi-Mu di surga dan peliharalah aku dari Fir'aun dan perbuatannya, dan peliharalah aku dari ...","Dan Allah membuat perumpamaan bagi orang-orang yang beriman, istri Fir'aun, ketika dia berkata, ""Ya Tuhanku, bangunkanlah untukku satu rumah di sisi-Mu dalam surga dan selamatkanlah aku dari Fir'aun dan perbuatannya, dan selamatkanlah aku dari ka...","Dan Allah membuat istri Firʻawn perumpamaan bagi orang-orang yang beriman, ketika ia berkata, ""Ya Tuhan-ku, bangunlah untukku sebuah rumah di sisi-Mu dalam surga dan selamatkanlah aku dari Firʻawn dan perbuatannya, dan selamatkanlah aku dari ka...",0.956486,0.966203,0.973615,1.922689,1.922689

In [ ]:
# df_max_sum.to_csv('../Semantic Analysis Results/max_sum_in_every_chapter.csv')

In [23]:
df = pd.read_csv('../Semantic Analysis Results/cosine_similarity.csv')

In [24]:
print('Fahd - Google mean - ', df['Fahd - Google'].mean())
print('Fahd - Google std - ', df['Fahd - Google'].std())
print('\n')

print('Kemenag -Google mean - ', df['Kemenag - Google'].mean())
print('Kemenag - Google std - ', df['Kemenag - Google'].std())
print('\n')

print('Fahd - Kemeag mean- ', df['Fahd - Kemenag'].mean())
print('Fahd - Kemeag std- ', df['Fahd - Kemenag'].std())

Fahd - Google mean -  0.8238365265844256
Fahd - Google std -  0.09974022608540699


Kemenag -Google mean -  0.835603050146492
Kemenag - Google std -  0.09048852411476206


Fahd - Kemeag mean-  0.8936215573400155
Fahd - Kemeag std-  0.07098203306125421

In [27]:
df['total'] = df['Fahd - Google'] + df['Kemenag - Google']
df.head()

,Unnamed: 0,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total,min sum
0,0,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244,1.861109,1.831757
1,1,2,3,"Orang-orang yang beriman kepada yang gaib, mendirikan shalat, dan menafkahkan sebagian rezeki yang Kami berikan kepada mereka.","(Yaitu) mereka yang beriman kepada yang gaib, melaksanakan salat, dan menginfakkan sebagian rezeki yang Kami berikan kepada mereka,","(yaitu) mereka yang beriman kepada yang gaib, yang mendirikan salat, dan menafkahkan sebagian rezeki yang Kami anugerahkan kepada mereka,",0.901631,0.898958,0.975567,1.800589,1.831757
2,2,2,4,"Dan orang-orang yang beriman kepada kitab yang diturunkan kepadamu dan kitab yang diturunkan sebelum kamu, dan kepada kehidupan akhirat, mereka adalah yakin.","dan mereka beriman kepada (Alquran) yang diturunkan kepadamu (Muhammad) dan (kitab-kitab) yang telah diturunkan sebelum engkau, dan mereka yakin akan adanya akhirat.","dan mereka yang beriman kepada Kitab (Al-Qur`ān) yang telah diturunkan kepadamu dan kitab-kitab yang telah diturunkan sebelummu, serta mereka yakin akan adanya (kehidupan) akhirat.",0.909239,0.857523,0.920318,1.766763,1.831757
3,3,2,5,Mereka itulah yang mendapat petunjuk dari Tuhannya dan mereka itulah orang-orang yang beruntung.,"Merekalah yang mendapat petunjuk dari Tuhannya, dan mereka itulah orang-orang yang beruntung.","Mereka itulah yang tetap mendapat petunjuk dari Tuhan mereka, dan merekalah orang-orang yang beruntung.",0.931456,0.992417,0.932781,1.923873,1.831757
4,4,2,6,"Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, engkau (Muhammad) beri peringatan atau tidak engkau beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.",1.000000,0.977054,0.977054,1.977054,1.831757

In [28]:
df['min sum'] = df.groupby(['Chapter'])['total'].transform('min')

df.head()

,Unnamed: 0,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total,min sum
0,0,2,2,Kitab ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa.,"Kitab (Alquran) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,","Kitab (Al-Qur`ān) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa,",0.915161,0.945948,0.962244,1.861109,1.013135
1,1,2,3,"Orang-orang yang beriman kepada yang gaib, mendirikan shalat, dan menafkahkan sebagian rezeki yang Kami berikan kepada mereka.","(Yaitu) mereka yang beriman kepada yang gaib, melaksanakan salat, dan menginfakkan sebagian rezeki yang Kami berikan kepada mereka,","(yaitu) mereka yang beriman kepada yang gaib, yang mendirikan salat, dan menafkahkan sebagian rezeki yang Kami anugerahkan kepada mereka,",0.901631,0.898958,0.975567,1.800589,1.013135
2,2,2,4,"Dan orang-orang yang beriman kepada kitab yang diturunkan kepadamu dan kitab yang diturunkan sebelum kamu, dan kepada kehidupan akhirat, mereka adalah yakin.","dan mereka beriman kepada (Alquran) yang diturunkan kepadamu (Muhammad) dan (kitab-kitab) yang telah diturunkan sebelum engkau, dan mereka yakin akan adanya akhirat.","dan mereka yang beriman kepada Kitab (Al-Qur`ān) yang telah diturunkan kepadamu dan kitab-kitab yang telah diturunkan sebelummu, serta mereka yakin akan adanya (kehidupan) akhirat.",0.909239,0.857523,0.920318,1.766763,1.013135
3,3,2,5,Mereka itulah yang mendapat petunjuk dari Tuhannya dan mereka itulah orang-orang yang beruntung.,"Merekalah yang mendapat petunjuk dari Tuhannya, dan mereka itulah orang-orang yang beruntung.","Mereka itulah yang tetap mendapat petunjuk dari Tuhan mereka, dan merekalah orang-orang yang beruntung.",0.931456,0.992417,0.932781,1.923873,1.013135
4,4,2,6,"Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, engkau (Muhammad) beri peringatan atau tidak engkau beri peringatan, mereka tidak akan beriman.","Sesungguhnya orang-orang kafir, sama saja bagi mereka, kamu beri peringatan atau tidak kamu beri peringatan, mereka tidak akan beriman.",1.000000,0.977054,0.977054,1.977054,1.013135

In [29]:
df_least_sum = df.loc[(df['min sum'] == df['total'])]

df_least_sum.to_csv('../Semantic Analysis Results/least_sum_in_every_chapter.csv')

In [30]:
df_least_sum

,Unnamed: 0,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag,total,min sum
136,136,2,138,"Pewarna Allah, dan siapakah yang lebih baik dari Allah dalam hal pewarnaan? Dan kita adalah hamba-hamba-Nya.","""Ṣibgah Allah"" Siapa yang lebih baik ṣibgah-nya daripada Allah? Dan kepada-Nya kami menyembah.",Ṣibgah Allah. Dan siapakah yang lebih baik Ṣibgah-nya daripada Allah? Dan hanya kepada-Nya-lah kami menyembah.,0.509156,0.503979,0.962761,1.013135,1.013135
337,337,3,54,"Dan mereka berencana, dan Allah pun berencana. Dan Allah adalah sebaik-baik perencana.","Dan mereka (orang-orang kafir) membuat tipu daya, maka Allah pun membalas tipu daya. Dan Allah sebaik-baik pembalas tipu daya.","Orang-orang kafir itu membuat tipu daya, dan Allah membalas tipu daya mereka itu. Dan Allah sebaik-baik pembalas tipu daya.",0.447102,0.476180,0.945183,0.923282,0.923282
581,581,4,98,"Kecuali orang-orang tertindas di antara laki-laki, perempuan, dan anak-anak yang tidak dapat merancang rencana dan juga tidak ditunjukkan jalan.","Kecuali mereka yang tertindas baik laki-laki atau perempuan dan anak-anak yang tidak berdaya dan tidak mengetahui jalan (untuk berhijrah),","kecuali mereka yang tertindas, baik laki-laki atau wanita ataupun anak-anak yang tidak mampu berdaya upaya dan tidak mengetahui jalan (untuk hijrah),",0.493049,0.612253,0.825672,1.105302,1.105302
762,762,5,103,"Allah tidak menjadikan sesuatu pun yang Bahiroh, Sa'ibah, Wasilah dan Hami, akan tetapi orang-orang yang kafir itu mengada-adakan kebohongan terhadap Allah, dan kebanyakan mereka tidak dapat berpikir.","Allah tidak pernah mensyariatkan adanya Baḥīrah, Sāibah, Waṣīlah dan Ḥām. Tetapi orang-orang kafir membuat-buat kedustaan terhadap Allah, dan kebanyakan mereka tidak mengerti.","Allah sekali-kali tidak pernah mensyariatkan adanya baḥīrah, sā`ibah, waṣīlah, dan ḥām. Akan tetapi, orang-orang kafir membuat-buat kedustaan terhadap Allah, dan kebanyakan mereka tidak mengerti.",0.609727,0.614196,0.964871,1.223923,1.223923
816,816,9,37,"Interkalasi hanyalah penambahan kekufuran yang dengannya orang-orang kafir disesatkan. Mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain agar mereka dapat menyempurnakan apa yang diharamkan Allah, dan dengan demikia...","Sesungguhnya pengunduran (bulan haram) itu hanya menambah kekafiran. Orang-orang kafir disesatkan dengan (pengunduran) itu, mereka menghalalkannya satu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menyesuaikan dengan bilangan...","Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menses...",0.346780,0.354384,0.879055,0.701164,0.701164
957,957,24,49,"Dan jika kebenaran itu milik mereka, mereka akan menerimanya dengan berserah diri.","Tetapi, jika kebenaran dipihak mereka, mereka datang kepadanya (Rasul) dengan patuh.","Tetapi jika keputusan itu untuk (kemaslahatan) mereka, mereka datang kepada rasul dengan patuh.",0.314125,0.711123,0.525156,1.025248,1.025248
986,986,33,14,"Dan jika surga itu datang kepada mereka dari daerahnya, kemudian mereka diminta untuk mengujinya, niscaya mereka akan mengujinya, dan mereka tidak akan tinggal di dalamnya kecuali sebentar saja.","Dan kalau (Yasrib) diserang dari segala penjuru, dan mereka diminta agar membuat kekacauan, niscaya mereka mengerjakannya; dan hanya sebentar saja mereka menunggu.","Kalau (Yaṡrib) diserang dari segala penjuru, kemudian diminta kepada mereka supaya murtad , niscaya mereka mengerjakannya dan mereka tiada akan menunda untuk murtad itu, melainkan dalam waktu yang singkat.",0.438173,0.428026,0.772614,0.866199,0.866199
1050,1050,47,5,Dia akan membimbing mereka dan mengatur urusan mereka dengan benar.,"Allah akan memberi petunjuk kepada mereka dan memperbaiki keadaan mereka,","Allah akan memberi pimpinan kepada mereka dan memperbaiki keadaan mereka,",0.570496,0.529459,0.896535,1.099954,1.099954
1086,1086,48,3,Dan Allah akan memberimu kemenangan besar.,dan agar Allah menolongmu dengan pertolongan yang kuat (banyak).,dan supaya Allah menolongmu dengan pertolongan yang kuat (banyak).,0.571637,0.564589,0.978105,1.136226,1.136226
1116,1116,49,4,"Sesungguhnya orang-orang yang menyeru kamu dari belakang bilik-bilik, kebanyakan mereka tidak dapat berpikir.",Sesungguhnya orang-orang yang memanggil engkau (Muhammad) dari luar kamar(mu) kebanyakan mereka tidak mengerti.,Sesungguhnya orang-orang yang memanggil kamu dari luar kamar(mu) kebanyakan mereka tidak mengerti.,0.608432,0.594599,0.930033,1.203031,1.203031
1144,1144,57,14,"Mereka berseru kepada orang-orang kafir, “Bukankah kami dahulu bersama kamu?” Mereka menjawab, “Benar, tetapi kamu telah mencobai dirimu sendiri, menanti-nantikan, dan ragu-ragu, dan angan-anganmu itu telah menipu kamu, hingga datanglah keputusan...","Orang-orang munafik memanggil orang-orang mukmin, ""Bukankah kami dahulu bersama kamu?"" Mereka menjawab, ""Benar, tetapi kamu mencelakakan dirimu sendiri, dan kamu hanya menunggu, meragukan (janji Allah) dan ditipu oleh angan-angan kosong sampai da...","Orang-orang munafik itu memanggil mereka (orang-orang mukmin) seraya berkata, ""Bukankah kami dahulu bersama-sama dengan kamu?"" Mereka menjawab, ""Benar, tetapi kamu mencelakakan dirimu sendiri dan menunggu (kehancuran kami), dan kamu ragu-ragu ser...",0.674975,0.692164,0.970708,1.367139,1.367139
1171,1171,58,12,"Wahai orang-orang yang beriman, jika kamu berunding dengan Rasulullah, hendaklah kamu bersedekah sebelum berunding dengan diri sendiri. Yang demikian itu lebih baik bagimu dan lebih suci. Jika kamu tidak menemukan sesuatu pun, maka sesungguhnya ...","Wahai orang-orang yang beriman! Apabila kamu mengadakan pembicaraan khusus dengan Rasul, hendaklah kamu mengeluarkan sedekah (kepada orang miskin) sebelum (melakukan) pembicaraan itu. Yang demikian itu lebih baik bagimu dan lebih bersih. Tetapi j...","Hai orang-orang beriman, apabila kamu mengadakan pembicaraan khusus dengan rasul hendaklah kamu mengeluarkan sedekah (kepada orang miskin) sebelum pembicaraan itu. Yang demikian itu adalah lebih baik bagimu dan lebih bersih; jika kamu tiada memp...",0.568286,0.570788,0.940321,1.139074,1.139074
1190,1190,59,9,"Dan orang-orang yang telah mapan dalam rumah tangga dan iman sebelum mereka, mencintai orang-orang yang berhijrah kepada mereka, dan tidak merasa dalam hati mereka kekurangan apa yang diberikan kepada mereka, dan mengutamakan mereka atas diri me...","Dan orang-orang (Ansar) yang telah menempati kota Madinah dan telah beriman sebelum (kedatangan) mereka (Muhajirin), mereka mencintai orang yang berhijrah ke tempat mereka. Dan mereka tidak menaruh keinginan dalam hati mereka terhadap apa yang di...","Dan orang-orang yang telah menempati kota Madinah dan telah beriman (Ansar) sebelum (kedatangan) mereka (Muhajirin), mereka mencintai orang yang berhijrah kepada mereka. Dan mereka tiada menaruh keinginan dalam hati mereka terhadap apa-apa yang ...",0.631410,0.645882,0.923515,1.277292,1.277292
1216,1216,60,11,"Dan jika salah seorang dari istri-istrimu telah meninggal dunia karena orang-orang kafir, lalu kamu menyiksa mereka, maka berikanlah kepada mereka (yang istrinya telah meninggal) harta yang telah mereka nafkahkan. Dan bertakwalah kepada Allah, ya...","Dan jika ada sesuatu (pengembalian mahar) yang belum kamu selesaikan dari istri-istrimu yang lari kepada orang-orang kafir, lalu kamu dapat mengalahkan mereka maka berikanlah (dari harta rampasan) kepada orang-orang yang istrinya lari itu sebanya...","Dan jika seseorang dari istri-istrimu lari kepada orang-orang kafir, lalu kamu mengalahkan mereka, maka bayarkanlah kepada orang-orang yang lari istrinya itu mahar sebanyak yang telah mereka bayar. Dan bertakwalah kepada Allah Yang kepada-Nya ka...",0.739962,0.720855,0.897275,1.460817,1.460817
1227,1227,61,9,"Dialah yang telah mengutus Rasul-Nya dengan petunjuk dan agama yang benar untuk dimenangkan-Nya atas segala agama, meskipun orang-orang yang mempersekutukan Allah tidak menyukainya.","Dialah yang mengutus Rasul-Nya dengan membawa petunjuk dan agama yang benar, untuk memenangkannya di atas segala agama meskipun orang-orang musyrik membencinya.",Dia-lah yang mengutus rasul-Nya dengan membawa petunjuk dan agama yang benar agar Dia memenangkannya di atas segala agama-agama meskipun orang musyrik benci.,0.725830,0.815879,0.914990,1.541708,1.541708
1235,1235,62,3,Dan belumlah ada yang menyusul mereka. Dan Dia Maha Perkasa lagi Maha Bijaksana.,"dan (juga) kepada kaum yang lain dari mereka yang belum bertemu dengan mereka. Dan Dialah Yang Mahaperkasa, Mahabijaksana.",dan (juga) kepada kaum yang lain dari mereka yang belum berhubungan dengan mereka. Dan Dia-lah Yang Maha Perkasa lagi Maha Bijaksana.,0.744296,0.707069,0.953348,1.451365,1.451365
1251,1251,63,8,"Mereka berkata, ""Jika kita kembali ke Madinah, orang-orang yang lebih terhormat pasti akan mengusir orang-orang yang lebih rendah hati darinya."" Padahal, kemuliaan itu milik Allah, milik Rasul-Nya, dan milik orang-orang mukmin, tetapi orang-oran...","Mereka berkata, ""Sungguh, jika kita kembali ke Madinah (kembali dari perang Bani Mustalik), pastilah orang yang kuat akan mengusir orang-orang yang lemah dari sana."" Padahal kekuatan itu hanyalah bagi Allah, Rasul-Nya dan bagi orang-orang mukmin,...","Mereka berkata, ""Sesungguhnya jika kita telah kembali ke Madinah, benar-benar orang yang kuat akan mengusir orang-orang yang lemah darinya"". Padahal kekuatan itu hanyalah bagi Allah, bagi rasul-Nya dan bagi orang-orang mukmin, tetapi orang-orang...",0.768815,0.740614,0.927333,1.509429,1.509429
1263,1263,64,9,"Hari di mana Dia mengumpulkan kalian pada Hari Perkumpulan—yaitu Hari Kerugian Bersama. Dan barangsiapa yang beriman kepada Allah dan beramal saleh, maka Dia akan menghapus kesalahan-kesalahannya dan memasukkannya ke dalam surga yang mengalir di...","(Ingatlah) pada hari (ketika) Allah mengumpulkan kamu pada hari berhimpun, itulah hari pengungkapan kesalahan-kesalahan. Dan barangsiapa beriman kepada Allah dan mengerjakan kebajikan niscaya Allah akan menghapus kesalahan-kesalahannya dan memasu...","(Ingatlah) hari (yang di waktu itu) Allah mengumpulkan kamu pada hari pengumpulan (untuk dihisab), itulah hari (waktu itu) ditampakkan kesalahan-kesalahan. Dan barang siapa yang beriman kepada Allah dan mengerjakan amal saleh, niscaya Allah akan...",0.714303,0.748169,0.905147,1.462472,1.462472
1280,1280,65,8,Dan berapa banyak negeri yang telah durhaka terhadap perintah Tuhannya dan para rasul-Nya? Maka Kami menimpakan azab yang pedih kepadanya dan Kami siksa dia dengan azab yang pedih.,"Dan betapa banyak (penduduk) negeri yang mendurhakai perintah Tuhan mereka dan rasul-rasul-Nya, maka Kami buat perhitungan terhadap penduduk negeri itu dengan perhitungan yang ketat, dan Kami azab mereka dengan azab yang mengerikan (di akhirat).","Dan berapalah banyaknya (penduduk) negeri yang mendurhakai perintah Tuhan mereka dan rasul-rasul-Nya, maka Kami hisab penduduk negeri itu dengan hisab yang keras, dan Kami azab mereka dengan azab yang mengerikan.",0.742112,0.671722,0.901488,1.413834,1.413834
1287,1287,66,3,"Dan ketika Nabi SAW menceritakan suatu pernyataan kepada salah seorang istrinya, dan ketika istrinya itu menceritakannya, lalu Allah memberitahukannya kepada beliau, beliau pun memberitahukannya sebagian dan mengabaikan sebagian lagi. Ketika Nab...","Dan ingatlah ketika secara rahasia Nabi membicarakan suatu peristiwa kepada salah seorang istrinya (Hafsah). Lalu dia menceritakan peristiwa itu (kepada Aisyah) dan Allah memberitahukan peristiwa itu kepadanya (Nabi), lalu (Nabi) memberitahukan (...",Dan ingatlah ketika nabi membicarakan secara rahasia kepada salah seorang dari istri-istrinya (ῌafṣah) suatu peristiwa. Maka tatkala (ῌafṣah) menceritakan peristiwa itu (kepada ʻĀ`isyah) dan Allah memberitahukan hal itu (semua pembicaraan ῌafṣah...,0.586661,0.734826,0.644268,1.321486,1.321486

In [33]:
df = pd.read_csv('../Semantic Analysis Results/cosine_similarity.csv')
maximum_difference = df.loc[(df['Fahd - Google']<0.5) & (df['Kemenag - Google'] < 0.5)]
maximum_difference

,Unnamed: 0,Chapter,Verse,Google Translate,Kemenag,King Fahd,Fahd - Google,Kemenag - Google,Fahd - Kemenag
337,337,3,54,"Dan mereka berencana, dan Allah pun berencana. Dan Allah adalah sebaik-baik perencana.","Dan mereka (orang-orang kafir) membuat tipu daya, maka Allah pun membalas tipu daya. Dan Allah sebaik-baik pembalas tipu daya.","Orang-orang kafir itu membuat tipu daya, dan Allah membalas tipu daya mereka itu. Dan Allah sebaik-baik pembalas tipu daya.",0.447102,0.476180,0.945183
816,816,9,37,"Interkalasi hanyalah penambahan kekufuran yang dengannya orang-orang kafir disesatkan. Mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain agar mereka dapat menyempurnakan apa yang diharamkan Allah, dan dengan demikia...","Sesungguhnya pengunduran (bulan haram) itu hanya menambah kekafiran. Orang-orang kafir disesatkan dengan (pengunduran) itu, mereka menghalalkannya satu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menyesuaikan dengan bilangan...","Sesungguhnya mengundur-undurkan bulan haram itu adalah menambah kekafiran, disesatkan orang-orang yang kafir dengan mengundur-undurkan itu, mereka menghalalkannya pada suatu tahun dan mengharamkannya pada tahun yang lain, agar mereka dapat menses...",0.346780,0.354384,0.879055
986,986,33,14,"Dan jika surga itu datang kepada mereka dari daerahnya, kemudian mereka diminta untuk mengujinya, niscaya mereka akan mengujinya, dan mereka tidak akan tinggal di dalamnya kecuali sebentar saja.","Dan kalau (Yasrib) diserang dari segala penjuru, dan mereka diminta agar membuat kekacauan, niscaya mereka mengerjakannya; dan hanya sebentar saja mereka menunggu.","Kalau (Yaṡrib) diserang dari segala penjuru, kemudian diminta kepada mereka supaya murtad , niscaya mereka mengerjakannya dan mereka tiada akan menunda untuk murtad itu, melainkan dalam waktu yang singkat.",0.438173,0.428026,0.772614

In [34]:
df_mean_fahd_google = df.groupby('Chapter')['Fahd - Google'].mean().reset_index()
df_mean_kemenag_google = df.groupby('Chapter')['Kemenag - Google'].mean().reset_index()


df_std_fahd_google = df.groupby('Chapter')['Fahd - Google'].std().reset_index()
df_std_kemenag_google = df.groupby('Chapter')['Kemenag - Google'].std().reset_index()

In [36]:
df_mean_fahd_google

    Chapter  Fahd - Google
0         2       0.820412
1         3       0.823510
2         4       0.818048
3         5       0.832971
4         9       0.807629
5        24       0.801286
6        33       0.829647
7        47       0.837569
8        48       0.807638
9        49       0.851366
10       57       0.872090
11       58       0.812554
12       59       0.827238
13       60       0.822395
14       61       0.871881
15       62       0.813571
16       63       0.850494
17       64       0.883796
18       65       0.823062
19       66       0.856229

In [37]:
df_mean_kemenag_google

    Chapter  Kemenag - Google
0         2          0.836795
1         3          0.844923
2         4          0.825697
3         5          0.833616
4         9          0.823944
5        24          0.823533
6        33          0.831098
7        47          0.826737
8        48          0.811333
9        49          0.837540
10       57          0.874068
11       58          0.831220
12       59          0.816448
13       60          0.856640
14       61          0.887574
15       62          0.832822
16       63          0.857629
17       64          0.895734
18       65          0.825740
19       66          0.890820

In [38]:
df_std_fahd_google

    Chapter  Fahd - Google
0         2       0.097392
1         3       0.107465
2         4       0.093525
3         5       0.090328
4         9       0.107501
5        24       0.114689
6        33       0.100417
7        47       0.090149
8        48       0.130074
9        49       0.118871
10       57       0.074235
11       58       0.101819
12       59       0.086739
13       60       0.053446
14       61       0.077694
15       62       0.079423
16       63       0.076423
17       64       0.080176
18       65       0.079651
19       66       0.094355

In [39]:
df_std_kemenag_google

    Chapter  Kemenag - Google
0         2          0.087024
1         3          0.086941
2         4          0.087390
3         5          0.086576
4         9          0.102026
5        24          0.088391
6        33          0.095863
7        47          0.099716
8        48          0.121718
9        49          0.108646
10       57          0.066069
11       58          0.103892
12       59          0.095010
13       60          0.064059
14       61          0.060840
15       62          0.070667
16       63          0.071066
17       64          0.073822
18       65          0.086929
19       66          0.066341

In [41]:
df_std_fahd_google['Fahd - Google'].mean()

0.09271860688492285

In [42]:
df_std_kemenag_google['Kemenag - Google'].mean()

0.08614932913816385

In [45]:
from keybert import KeyBERT
kw_model = KeyBERT(model = 'LazarusNLP/all-indo-e5-small-v4')